modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Absolucy/backup-mod/issues"
license = "MPL-2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Lucy's Backup Mod"
authors = "Absolucy <lucy@absolucy.moe>"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${forge_kotlin_version}]"
ordering = "AFTER"
side = "BOTH"